// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[example]")
{
    REQUIRE(ageChecker(18)==1);
    REQUIRE(ageChecker(12)==0);
    REQUIRE(ageChecker(-18)==0);
    REQUIRE(ageChecker(13)==1);
        
}

// =====================
// tests for exercise 2
// ---------------------


